server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:13306/urlmanagerservice
    username: danielngo1998
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/database/changelog/changelog_master.xml

io:
  vef:
    academy:
      bootstrap:
        servers: 192.168.99.100:9092,192.168.99.100:9094,192.168.99.100:9094

logging:
  level:
    io.vef.academy: DEBUG
    liquibase: INFO